### PR TITLE
Added support SPI v1 HAL driver

### PR DESCRIPTION
**Pull request by HorrorTroll**
Added support SPI v1 HAL driver, it does init and running on QMK. But something wrong that `SCK / MOSI / MISO lines` doesn't sending signal if key matrix is not pressing. If you have some free time for reviewing, can you try out and debug it?

Setup I was try testing is using QMK Quantum Painter with LCD ST7735 (160x80) module.

Video showcase of testing and issues:

https://github.com/qmk-arterytek/ChibiOS-Contrib/assets/24840279/5678cfd5-0bff-4075-ae23-2e75fb43f66c

### CODE REVIEW

**Comment by zhaqian12** [comment]
> Added support SPI v1 HAL driver, it does init and running on QMK. But something wrong that `SCK / MOSI / MISO lines` doesn't sending signal if key matrix is not pressing. If you have some free time for reviewing, can you try out and debug it?
> 
> Setup I was try testing is using QMK Quantum Painter with LCD ST7735 (160x80) module.
> 
> Video showcase of testing and issues:
> 
>  IMG_5793.mov

Could you provide the code or repository about this bug for testing？Thanks.

**Comment by HorrorTroll** [comment]
> Could you provide the code or repository about this bug for testing？Thanks.

~~Ahh, sorry I forgot that. Here is the code I've just uploaded. Keyboard should be on `handwired/onekey/at32_start_f415`
https://github.com/qmk-arterytek/qmk_firmware/commit/3c311f1a79c723119ec54d0f8d5e626b472c6a02~~

Nvm, I've just found the issue and already fixed, All work now. Feel free to reviewing this PR now

**Comment by zhaqian12** [comment]
I tested the spi on my repo, with the same code. But I don't have st7735 to use now，so the test platform is at32f405 which with the same spi peripheral ip.  It worked well with spi.  So I think maybe it's a configuration error.

**Comment by zhaqian12** [comment]
> I tested the spi on my repo, with the same code. But I don't have st7735 to use now，so the test platform is at32f405 which with the same spi peripheral ip. It worked well with spi. So I think maybe it's a configuration error.

software cs

**Comment by HorrorTroll** [comment]
> > I tested the spi on my repo, with the same code. But I don't have st7735 to use now，so the test platform is at32f405 which with the same spi peripheral ip. It worked well with spi. So I think maybe it's a configuration error.
> 
> software cs

It was the problem with tick-less on ChibiOS side anyway, I've been asking QMK for some explaination what that mean. Since it was based on STM32F1, tick-less was supposed to be needed 32-bit timer for it. But F1 doesn't have any 32-bit timer so it have to be used at classic periodic tick, that was fixed the issues.

Probably would noted this and figured out how to make it running at tick-less, since every Artery chip does support 32-bit timers

**Comment by zhaqian12** [comment]
> > > I tested the spi on my repo, with the same code. But I don't have st7735 to use now，so the test platform is at32f405 which with the same spi peripheral ip. It worked well with spi. So I think maybe it's a configuration error.
> > 
> > 
> > software cs
> 
> It was the problem with tick-less on ChibiOS side anyway, I've been asking QMK for some explaination what that mean. Since it was based on STM32F1, tick-less was supposed to be needed 32-bit timer for it. But F1 doesn't have any 32-bit timer so it have to be used at classic periodic tick, that was fixed the issues.
> 
> Probably would noted this and figured out how to make it running at tick-less, since every Artery chip does support 32-bit timers

Is this a problem with os tick? If you used a 32-bit timer as the chibios tick, then its configuration is now incorrect because the 32-bit extension of at32 needs to be configured. Look at my repo commit:https://github.com/zhaqian12/ChibiOS-Contrib/commit/f9922a099f178e11871ff0c791366b96da5ed862. Or just use it as a 16-bits timer.

**Review by zhaqian12 — APPROVED** [review]

**Comment by HorrorTroll** [comment]
> > > > I tested the spi on my repo, with the same code. But I don't have st7735 to use now，so the test platform is at32f405 which with the same spi peripheral ip. It worked well with spi. So I think maybe it's a configuration error.
> > > 
> > > 
> > > software cs
> > 
> > 
> > It was the problem with tick-less on ChibiOS side anyway, I've been asking QMK for some explaination what that mean. Since it was based on STM32F1, tick-less was supposed to be needed 32-bit timer for it. But F1 doesn't have any 32-bit timer so it have to be used at classic periodic tick, that was fixed the issues.
> > Probably would noted this and figured out how to make it running at tick-less, since every Artery chip does support 32-bit timers
> 
> Is this a problem with os tick? If you used a 32-bit timer as the chibios tick, then its configuration is now incorrect because the 32-bit extension of at32 needs to be configured. Look at my repo commit:[zhaqian12@f9922a0](https://github.com/zhaqian12/ChibiOS-Contrib/commit/f9922a099f178e11871ff0c791366b96da5ed862). Or just use it as a 16-bits timer.

Ahh, I didn't knew that. Thanks, lemme try it out and see.

**Comment by HorrorTroll** [comment]
Tested and it work flawless, thanks.

**Pull request merged**
