### PR TITLE
Clean up and init flexible DMA

### PR DESCRIPTION
**Pull request by HorrorTroll**
I'm just clean up some leftover, and try to init flexible DMA. Testing on SPI and it did work with channel 1/2/3/4, but 5/6/7 causing the board not init.

Probably missing something? Can you take a look and try it out?

Reopen new pr: #13

### CODE REVIEW

**Comment by zhaqian12** [comment]
Works well with my pwm dma driver and can provide any configuration code that has errors?

**Comment by HorrorTroll** [comment]
> Works well with my pwm dma driver and can provide any configuration code that has errors?

I’m just added those to `mcuconf.h` file on my board folder:
```
#undef AT32_DMA_USE_DMAMUX
#define AT32_DMA_USE_DMAMUX TRUE

#undef AT32_SPI_SPI1_RX_DMAMUX_CHANNEL
#define AT32_SPI_SPI1_RX_DMAMUX_CHANNEL 5

#undef AT32_SPI_SPI1_TX_DMAMUX_CHANNEL
#define AT32_SPI_SPI1_TX_DMAMUX_CHANNEL 6
```
And it didn’t work.

But if I’ve try this, the board is init normally:
```
#undef AT32_DMA_USE_DMAMUX
#define AT32_DMA_USE_DMAMUX TRUE

#undef AT32_SPI_SPI1_RX_DMAMUX_CHANNEL
#define AT32_SPI_SPI1_RX_DMAMUX_CHANNEL 1

#undef AT32_SPI_SPI1_TX_DMAMUX_CHANNEL
#define AT32_SPI_SPI1_TX_DMAMUX_CHANNEL 2
```

**Comment by zhaqian12** [comment]
> > Works well with my pwm dma driver and can provide any configuration code that has errors?
> 
> I’m just added those to `mcuconf.h` file on my board folder:
> 
> ```
> #undef AT32_DMA_USE_DMAMUX
> #define AT32_DMA_USE_DMAMUX TRUE
> 
> #undef AT32_SPI_SPI1_RX_DMAMUX_CHANNEL
> #define AT32_SPI_SPI1_RX_DMAMUX_CHANNEL 5
> 
> #undef AT32_SPI_SPI1_TX_DMAMUX_CHANNEL
> #define AT32_SPI_SPI1_TX_DMAMUX_CHANNEL 6
> ```
> 
> And it didn’t work.
> 
> But if I’ve try this, the board is init normally:
> 
> ```
> #undef AT32_DMA_USE_DMAMUX
> #define AT32_DMA_USE_DMAMUX TRUE
> 
> #undef AT32_SPI_SPI1_RX_DMAMUX_CHANNEL
> #define AT32_SPI_SPI1_RX_DMAMUX_CHANNEL 1
> 
> #undef AT32_SPI_SPI1_TX_DMAMUX_CHANNEL
> #define AT32_SPI_SPI1_TX_DMAMUX_CHANNEL 2
> ```

The board is not initialized? This means that even usb does not have enumeration or just spi does not work.

**Comment by HorrorTroll** [comment]
> The board is not initialized? This means that even usb does not have enumeration or just spi does not work.

It mean SPI don't work. Only USB working, everything else is just freezing.

**Pull request closed without merging**
