### PR TITLE
[Feat]Add at32 tmr low level driver v1.

### PR DESCRIPTION
**Pull request by zhaqian12**
Add at32 tmr driver, but without complete testing. Could you review it if you have a minute? Thanks a lot!

### CODE REVIEW

**Comment by HorrorTroll** [comment]
I've just take a look and push some commit to clean up a bit. Here are the list I've did testing them out:
### Testing with Piezo speaker:
**PWM Software:**
- GPTD1, GPTD3, GPTD4, GPTD5, GPTD9, GPTD10, GPTD11 work.
- PWMD1 (TIM1_CH1), PWMD3 (TIM3_CH1), PWMD4 (TIM4_CH1), PWMD5 (TIM5_CH1) work (*).

**PWM Hardware:**
- PWMD1 (TIM1_CH1) work.
### Testing with WS2812 LED:
- PWMD1 (TIM1_CHx), PWMD3 (TIM3_CHx), PWMD4 (TIM4_CHx) work.
- PWMD5 (TIM5_CHx) not work (**).
### Notes:
- (*) Timer 5 running at plus mode (32-bit) is working normally.
- (**) Timer 5 running at plus mode (32-bit) is not working.
- (***) PWMD2 and GPTD2 can't use since Timer 2 using for SysTick.

**Review by HorrorTroll — APPROVED** [review]

**Comment by zhaqian12** [comment]
Thanks a lot for you help. About the problem "PWMD5 (TIM5_CHx) not work (**)", was it tested in qmk ws2812 driver? If so, could you update the qmk repository about the testing code? I'll try to replicate it.

---

It worked well in my test.

**Comment by HorrorTroll** [comment]
> Thanks a lot for you help. About the problem "PWMD5 (TIM5_CHx) not work (**)", was it tested in qmk ws2812 driver? If so, could you update the qmk repository about the testing code? I'll try to replicate it.
> 
> It worked well in my test.

It strange that it didn't work on my side, here the branch of it. Could you test it again?
<https://github.com/qmk-arterytek/qmk_firmware/tree/arterytek_pwm>

**Comment by zhaqian12** [comment]
> > Thanks a lot for you help. About the problem "PWMD5 (TIM5_CHx) not work (**)", was it tested in qmk ws2812 driver? If so, could you update the qmk repository about the testing code? I'll try to replicate it.
> > It worked well in my test.
> 
> It strange that it didn't work on my side, here the branch of it. Could you test it again? https://github.com/qmk-arterytek/qmk_firmware/tree/arterytek_pwm

I tested it today, and it worked fine. But I encountered a problem at the beginning of the test: it doesn't work when I didn't enable any more rgb matrix effects, and after looking at the register, I found that TMR5 is not initialized, that is, ws2812_init is not called. Maybe this is some conflict on the qmk side.

**Comment by HorrorTroll** [comment]
> I tested it today, and it worked fine. But I encountered a problem at the beginning of the test: it doesn't work when I didn't enable any more rgb matrix effects, and after looking at the register, I found that TMR5 is not initialized, that is, ws2812_init is not called. Maybe this is some conflict on the qmk side.

Thanks, I've just checking out and it seem that it my fault at this. Since the code shouldn't be this:
```c
#if !defined(STM32F1XX) && !defined(STM32L0XX) && !defined(STM32L1XX) && !defined(AT32F415)
#    define WS2812_PWM_TIMER_32BIT_PWMD2 1
#endif
#if !defined(STM32F1XX) && !defined(AT32F415)
#    define WS2812_PWM_TIMER_32BIT_PWMD5 1
#endif
```
It should be this:
```c
#if !defined(STM32F1XX) && !defined(STM32L0XX) && !defined(STM32L1XX)
#    define WS2812_PWM_TIMER_32BIT_PWMD2 1
#endif
#if !defined(STM32F1XX)
#    define WS2812_PWM_TIMER_32BIT_PWMD5 1
#endif
```
And everything work perfectly now. By the way, I think I just encounter weird bug. I'm try testing WS2812 at SPI driver with OLED screen, somehow if the WS2812 have more than 3 LED. It causing out of SRAM (even though it have 32 KB) and giving I2C crashed. I've try Logic Analyzer to see and it showing like this (arrow point to where I2C crashed).

image

**Comment by zhaqian12** [comment]
> And everything work perfectly now. By the way, I think I just encounter weird bug. I'm try testing WS2812 at SPI driver with OLED screen, somehow if the WS2812 have more than 3 LED. It causing out of SRAM (even though it have 32 KB) and giving I2C crashed. I've try Logic Analyzer to see and it showing like this (arrow point to where I2C crashed).

> It causing out of SRAM (even though it have 32 KB)
Did it build successfully while linking the objects? 
>giving I2C crashed
Is master error or slave error?

Any way, provide the code of keyboard is better. Thanks!

**Comment by HorrorTroll** [comment]
> > It causing out of SRAM (even though it have 32 KB)
> > Did it build successfully while linking the objects?
> > giving I2C crashed
> > Is master error or slave error?
> 
> Any way, provide the code of keyboard is better. Thanks!

It was using both I2C master and SPI master, here is my board code that I've been use to test on breadboard. Every setting should be there.
<https://github.com/qmk-arterytek/qmk_firmware/tree/arterytek_pwm/keyboards/horrortroll/artemisia>

**Comment by HorrorTroll** [comment]
> It was using both I2C master and SPI master, here is my board code that I've been use to test on breadboard. Every setting should be there. https://github.com/qmk-arterytek/qmk_firmware/tree/arterytek_pwm/keyboards/horrortroll/artemisia

image
Further check with SWD Debug on GDB + OpenOCD. It look like the BUSY FLAG errata causing the bug,

For more info about that errata on STM32F103 docs:
[Errata 2.9.7 - I2C analog filter may provide wrong value, locking BUSY flag and preventing master mode
entry](https://www.st.com/resource/en/errata_sheet/es0340-stm32f101xcde-stm32f103xcde-device-errata-stmicroelectronics.pdf)

**Comment by zhaqian12** [comment]
> > > It causing out of SRAM (even though it have 32 KB)
> > > Did it build successfully while linking the objects?
> > > giving I2C crashed
> > > Is master error or slave error?
> > 
> > 
> > Any way, provide the code of keyboard is better. Thanks!
> 
> It was using both I2C master and SPI master, here is my board code that I've been use to test on breadboard. Every setting should be there. https://github.com/qmk-arterytek/qmk_firmware/tree/arterytek_pwm/keyboards/horrortroll/artemisia

> somehow if the WS2812 have more than 3 LED. It causing out of SRAM (even though it have 32 KB)

I tested it  yesterday, it work normal without oled connection(i2c only send address), and number of leds was more than 24. 

> giving I2C crashed

Try to find a oled to test. About busy flag, try to restart i2c(reset and reconfig i2c reg, then try to communicate).

**Comment by HorrorTroll** [comment]
> I tested it yesterday, it work normal without oled connection(i2c only send address), and number of leds was more than 24.
> 
> > giving I2C crashed
> 
> Try to find a oled to test. About busy flag, try to restart i2c(reset and reconfig i2c reg, then try to communicate).

I've just found the issues, the problem is that I'm connect the VCC on WS2812 to 3.3V instead 5V. So I guess the power is not draw enough and causing other device like OLED crashed. At today I've did connect VCC on WS2812 to 5V and testing, it didn't have any problem now.

Everything run perfectly now, this PR could be merged now. Thanks for your work ❤️

**Pull request merged**
